apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: uber
 namespace: default
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: uber
       version: v1
   spec:
     containers:
     - name: uber
       image: training-project:v1
       imagePullPolicy: Never
       ports:
       - containerPort: 7000

