apiVersion: v1
kind: Secret
metadata:
  name: training-project-secret
type: Opaque
data:
  UBER_CLIENT_ID: VW5kbGdERm8teDJLM211d2NKRnVQNmZiSWJnZVBOc1o=
  UBER_CLIENT_SECRET: ZXozcHhSTkQyb0k3Y2ZOdTZTVDFRcjNFMWhHVmUtd0tMbzFrUm4zXw==
